export const manColor = [ '#01f1da', '#00adff' ];
export const womanColor = [ '#ff9954', '#ff4e77' ];
export const grey = '#9e9e9e';

export const ethnicityPickList = {
    "Ainu": "Ainu",
    "Bonin Islanders": "Bonin Islanders",
    "Ryukyuans" : "Ryukyuans",
    "Yamato" : "Yamato",
    "Chinese" : "Chinese",
    "Koreans" : "Koreans",
    "Filipinos" : "Filipinos",
    "Brazilians" : "Brazilians",
    "Vietnamese" : "Vietnamese",
    "Peruvians" : "Peruvians",
    "Others" : "Others",
};
export const prefecturePickList = {
    "Hokkaido" : "Hokkaido",
    "Aomori" : "Aomori",
    "Iwate" : "Iwate",
    "Miyagi" : "Miyagi",
    "Akita" : "Akita",
    "Yamagata" : "Yamagata",
    "Fukushima" : "Fukushima",
    "Ibaraki" : "Ibaraki",
    "Tochigi" : "Tochigi",
    "Gunma" : "Gunma",
    "Saitama" : "Saitama",
    "Chiba" : "Chiba",
    "Tokyo" : "Tokyo",
    "Kanagawa" : "Kanagawa",
    "Niigata" : "Niigata",
    "Toyama" : "Toyama",
    "Ishikawa" : "Ishikawa",
    "Fukui" : "Fukui",
    "Yamanashi" : "Yamanashi",
    "Nagano" : "Nagano",
    "Gifu" : "Gifu",
    "Shizuoka" : "Shizuoka",
    "Aichi" : "Aichi",
    "Mie" : "Mie",
    "Shiga" : "Shiga",
    "Kyoto" : "Kyoto",
    "Osaka" : "Osaka",
    "Hyogo" : "Hyogo",
    "Nara" : "Nara",
    "Wakayama" : "Wakayama",
    "Tottori" : "Tottori",
    "Shimane" : "Shimane",
    "Okayama" : "Okayama",
    "Hiroshima" : "Hiroshima",
    "Yamaguchi" : "Yamaguchi",
    "Tokushima" : "Tokushima",
    "Kagawa" : "Kagawa",
    "Ehime" : "Ehime",
    "Kochi" : "Kochi",
    "Fukuoka" : "Fukuoka",
    "Miyazaki" : "Miyazaki",
    "Nagasaki" : "Nagasaki",
    "Kumamoto" : "Kumamoto",
    "Kagoshima" : "Kagoshima",
    "Saga" : "Saga",
    "Oita" : "Oita",
    "Okinawa" : "Okinawa",
};
